name: genet_church_portal
description: "EGC database front end"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.6.1
  dio: ^5.9.0
  go_router: ^16.2.0
  flutter_svg: ^2.2.0
  shimmer: ^3.0.0
  flutter_animate: ^4.5.2
  fl_chart: ^1.0.0
  flutter_hooks: ^0.21.3
  hooks_riverpod: ^2.6.1
  iconsax: ^0.0.8
  image_picker: ^1.2.0
  intl: ^0.20.2
  flutter_secure_storage: ^9.2.4
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.5.3
  timeago: ^3.7.1
  csv: ^6.0.0
  google_fonts: ^6.2.1
  abushakir: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  flutter_native_splash: ^2.4.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  color_dark: "#121212"
  image_dark: assets/images/logo.png

  android_12:
    image: assets/images/logo.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/logo.png
    icon_background_color_dark: "#121212"

  web: false

flutter:

  uses-material-design: true

  assets:
    - assets/images/
